### ISSUE TITLE
Better Design

### ISSUE THREAD

**Issue by erfjab** [Tsepahvand/Traffic-Checker#1]
درود، توصیه میکنم کدتون رو دایرکتوری بندی کنید.
مثلا موارد مرتبط با دیتابیس در دایرکتوری دیتابیس
و فانکشن هایی مثل ساخت، یک فایل، مدیریت یک فایل جدا باشد.
برای بات تلگرامی دایرکتوری router بزنید
و برای هر کامند و یا پروسه یه فایل اختصاصی بزنید.
اینجوری توسعه‌ و مدیریت‌تون راحت تر خواهد بود عزیز.
موفق باشید

**Comment by Tsepahvand** [comment]
> باشید

بله
خیلی ممنون از پیشنهادتون
حتما در اپدیت های بعدی اضافه میشه

**Comment by Tsepahvand** [comment]
> درود، توصیه میکنم کدتون رو دایرکتوری بندی کنید.
> مثلا موارد مرتبط با دیتابیس در دایرکتوری دیتابیس
> و فانکشن هایی مثل ساخت، یک فایل، مدیریت یک فایل جدا باشد.
> برای بات تلگرامی دایرکتوری router بزنید
> و برای هر کامند و یا پروسه یه فایل اختصاصی بزنید.
> اینجوری توسعه‌ و مدیریت‌تون راحت تر خواهد بود عزیز.
> موفق باشید 

بله
خیلی ممنون از پیشنهادتون
حتما در اپدیت های بعدی اضافه میشه
